// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 为某个枚举单独设置错误码
func IsNeedLogin(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_NEED_LOGIN.String() && e.Code == 401
}

// 为某个枚举单独设置错误码
func ErrorNeedLogin(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_NEED_LOGIN.String(), fmt.Sprintf(format, args...))
}

func IsDbFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DB_FAILED.String() && e.Code == 500
}

func ErrorDbFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_DB_FAILED.String(), fmt.Sprintf(format, args...))
}

// 订单已评价
func IsOrderReviewed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ORDER_REVIEWED.String() && e.Code == 400
}

// 订单已评价
func ErrorOrderReviewed(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_ORDER_REVIEWED.String(), fmt.Sprintf(format, args...))
}

// 订单未评价
func IsOrderNotReviewed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ORDER_NOT_REVIEWED.String() && e.Code == 400
}

// 订单未评价
func ErrorOrderNotReviewed(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_ORDER_NOT_REVIEWED.String(), fmt.Sprintf(format, args...))
}

// 评价已回复
func IsReviewReplied(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_REVIEW_REPLIED.String() && e.Code == 400
}

// 评价已回复
func ErrorReviewReplied(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_REVIEW_REPLIED.String(), fmt.Sprintf(format, args...))
}

// 未发表评价
func IsReviewNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_REVIEW_NOT_FOUND.String() && e.Code == 404
}

// 未发表评价
func ErrorReviewNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_REVIEW_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

// 水平越权错误
func IsHorizontalPermissionDenied(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_HORIZONTAL_PERMISSION_DENIED.String() && e.Code == 403
}

// 水平越权错误
func ErrorHorizontalPermissionDenied(format string, args ...interface{}) *errors.Error {
	return errors.New(403, ErrorReason_HORIZONTAL_PERMISSION_DENIED.String(), fmt.Sprintf(format, args...))
}

// 申述已处理
func IsAppealAlreadyProcessed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_APPEAL_ALREADY_PROCESSED.String() && e.Code == 400
}

// 申述已处理
func ErrorAppealAlreadyProcessed(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_APPEAL_ALREADY_PROCESSED.String(), fmt.Sprintf(format, args...))
}
